version: '3.1'

services:
  webserv:
    build: .
    image: webserv:arch
    container_name: webserv
    ports:
      - "80:80"
      - "8080:8080"
      - "8000:8000"
      - "443:443"
    volumes:
      - ../../:/Webserv